// automatically generated by the FlatBuffers compiler, do not modify

package com.mz.fastapp.flatbuffers_py2java;

@SuppressWarnings("unused")
public final class FlatBuffersResponseType {
  private FlatBuffersResponseType() { }
  public static final byte Success = 0;
  public static final byte Error = 1;
  public static final byte ThreadOccupation = 2;

  public static final String[] names = { "Success", "Error", "ThreadOccupation", };

  public static String name(int e) { return names[e]; }
}

