// automatically generated by the FlatBuffers compiler, do not modify

package com.mz.fastapp.flatbuffers_py2java;

@SuppressWarnings("unused")
public final class FlatBuffersJavaTypeEnum {
  private FlatBuffersJavaTypeEnum() { }
  public static final byte Ref = 0;
  public static final byte Bytes = 1;
  public static final byte String = 2;
  public static final byte Null = 3;
  public static final byte Byte = 4;
  public static final byte Short = 5;
  public static final byte Int = 6;
  public static final byte Long = 7;
  public static final byte Float = 8;
  public static final byte Double = 9;
  public static final byte Boolean = 10;
  public static final byte Char = 11;
  public static final byte Array = 12;

  public static final String[] names = { "Ref", "Bytes", "String", "Null", "Byte", "Short", "Int", "Long", "Float", "Double", "Boolean", "Char", "Array", };

  public static String name(int e) { return names[e]; }
}

