// automatically generated by the FlatBuffers compiler, do not modify

package com.mz.fastapp.flatbuffers_py2java;

@SuppressWarnings("unused")
public final class FlatBuffersRequestType {
  private FlatBuffersRequestType() { }
  public static final byte GetClass = 0;
  public static final byte NewObject = 1;
  public static final byte GetFieldObject = 2;
  public static final byte SetFieldObject = 3;
  public static final byte CallMethod = 4;
  public static final byte NewProxyObject = 5;
  public static final byte ProxyInvoke = 6;
  public static final byte DeleteObject = 7;
  public static final byte GetValue = 8;

  public static final String[] names = { "GetClass", "NewObject", "GetFieldObject", "SetFieldObject", "CallMethod", "NewProxyObject", "ProxyInvoke", "DeleteObject", "GetValue", };

  public static String name(int e) { return names[e]; }
}

